In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('services.csv')

In [9]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [13]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [14]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [15]:
df['website']

0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
5                        NaN
6                        NaN
7                        NaN
8                        NaN
9                        NaN
10                       NaN
11                       NaN
12                       NaN
13                       NaN
14                       NaN
15                       NaN
16                       NaN
17                       NaN
18                       NaN
19                       NaN
20                       NaN
21    http://www.example.com
22    http://www.example.com
Name: website, dtype: object

In [17]:
df[['audience','description']]

,audience,description
0,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...
1,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...
2,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...
3,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...
4,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...
5,Any age,A multipurpose center offering a wide variety ...
6,"Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...
7,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...
8,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b..."
9,NaN,"Provides general reading and media materials, ..."
10,NaN,"Provides general reading materials, including ..."
11,"Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...
12,NaN,"Provides general reading materials, including ..."
13,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte..."
14,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...
15,NaN,Provides emergency assistance including food a...
16,NaN,"Provides emergency food, clothing and furnitur..."
17,NaN,"By appointment only, Project Smile provides a ..."
18,NaN,Provides free medical and dental care to those...
19,NaN,no unrequired fields for this service
20,NaN,just a test service
21,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

In [22]:
df1=pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [23]:
df1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN